<a href="https://colab.research.google.com/github/ntanhthi/DATA-SCIENCE-CLASS-/blob/main/Numpy_Basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

list_data = [1,2,3,4,5]
array_from_list = np.array(list_data)
print(array_from_list)

[1 2 3 4 5]


In [ ]:
import numpy as np

list_data = [1,2,3,4,5]
arr = np.array(list_data)
print("arr:", arr)
print("Shape of arr:", arr.shape)
print("Size of arr:", arr.size)
print("Type of arr:", arr.dtype)
print("Dimension of arr:", arr.ndim)

arr: [1 2 3 4 5]
Shape of arr: (5,)
Size of arr: 5
Type of arr: int64
Dimension of arr: 1


In [ ]:
import numpy as np

zeros_array = np.zeros((2,5))
print(zeros_array)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
import numpy as np

ones_array = np.ones((3,3))
print(ones_array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
import numpy as np

full_array = np.full((4,4), 7)
print(full_array)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [ ]:
import numpy as np

arange_array = np.arange(0, 10, 2)
print(arange_array)

[0 2 4 6 8]


In [ ]:
import numpy as np
#np.eye là 1 hàm dùng để tạo 1 ma trận đơn vị, trong đó phần tử trên đường chéo chính là 1 và các phần tử còn lại là 0
eye_matrix = np.eye(3)
print(eye_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import numpy as np

#np.random.seed(2024)
random_array = np.random.rand(3,3)
print(random_array)

[[0.44829582 0.01910695 0.75259834]
 [0.60244854 0.96177758 0.66436865]
 [0.60662962 0.44915131 0.22535416]]


In [ ]:
import numpy as np
np.random.seed(2024)
randint_array = np.random.randint(1, 10, (3,3))
print(randint_array)

[[9 1 1]
 [5 8 2]
 [4 3 1]]


In [ ]:
import numpy as np

arr1d = np.array([1,2,3,4,5])
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])

first_element = arr1d[0]
print("Phần tử đầu tiên của arr1d:", first_element)

last_element = arr1d[-1]
print("Phần tử cuối cùng của arr1d:", last_element)

first_row = arr2d[0]
print("Dòng đầu tiên của arr2d:", first_row)

Phần tử đầu tiên của arr1d: 1
Phần tử cuối cùng của arr1d: 5
Dòng đầu tiên của arr2d: [1 2 3]


In [ ]:
import numpy as np

arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr2d)

element_1_2 = arr2d[1,1]
print(element_1_2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
5


In [ ]:
import numpy as np

arr1d = np.array([1,2,3,4,5])
#Slicing trong NumPy cho phép ta trích xuất 1 phần của mãng bằng cách chị định khoàn mục
sliced_arr1d = arr1d[1:4]
print("arr1d:", sliced_arr1d)
print("Sclicing arr1d từ chỉ số đến 3:", sliced_arr1d)

arr1d: [2 3 4]
Sclicing arr1d từ chỉ số đến 3: [2 3 4]


In [ ]:
import numpy as np

arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])

sliced_arr2d = arr2d[1:3, 1:]
print("arr2d:", arr2d)
print("Slicing arr2d từ hàng 1 đến 2 và cộ t1 đến cuối cùng: \n",sliced_arr2d)

arr2d: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Slicing arr2d từ hàng 1 đến 2 và cộ t1 đến cuối cùng: 
 [[5 6]
 [8 9]]


In [ ]:
import numpy as np

arr_1 = np.array([1,2,3])
arr_2 = np.array([4,5,6])

# Nối hai mảng theo trục ngang(axis =0)
arr_3 = np.hstack((arr_1,arr_2))
# In kết quả
print("Mảng 1:\n", arr_1)
print("Mảng 2:\n", arr_2)
print("Mảng nối theo trục ngang:\n", arr_3)

Mảng 1:
 [1 2 3]
Mảng 2:
 [4 5 6]
Mảng nối theo trục ngang:
 [1 2 3 4 5 6]


In [ ]:
import numpy as np

arr_1 = np.array([1,2,3])
arr_2 = np.array([4,5,6])

# Nối hai mảng theo trục dọc(axis =1)
arr_3 = np.vstack((arr_1,arr_2))
# In kết quả
print("Mảng 1:\n", arr_1)
print("Mảng 2:\n", arr_2)
print("Mảng nối theo trục ngang:\n", arr_3)

Mảng 1:
 [1 2 3]
Mảng 2:
 [4 5 6]
Mảng nối theo trục ngang:
 [[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np

# Tạo hai array 2D
arr_1 = np.array([[1,2,3], [4,5,6]])
arr_2 = np.array([[7,8,9], [10,11,12]])

# Nối hai mảng theo trục doc axis =0
arr_3 = np.concatenate((arr_1,arr_2),axis=0)

# Nối hai mảng theo trục ngang axis =1
arr_4 = np.concatenate((arr_1,arr_2),axis=1)


# In kết quả
print("Mảng 1:\n", arr_1)
print("Mảng 2:\n", arr_2)
print("Mảng nối theo trục doc (axis=0):\n", arr_3)
print("Mảng nối theo trục ngang (axis=1):\n", arr_4)


Mảng 1:
 [[1 2 3]
 [4 5 6]]
Mảng 2:
 [[ 7  8  9]
 [10 11 12]]
Mảng nối theo trục doc (axis=0):
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Mảng nối theo trục ngang (axis=1):
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [ ]:
import numpy as np

arr_1 = np.array([1,2,3])
# 1D -> 2D
arr_2 = arr_1[np.newaxis, :]
# 2D -> 5D
arr_3 = arr_2[np.newaxis,:,np.newaxis,:,np.newaxis]
# In kết quả
print("Mảng 1:\n", arr_1, arr_1.shape)
print("Mảng 2:\n", arr_2, arr_2.shape)
print("Mảng 3:\n", arr_3, arr_3.shape)

Mảng 1:
 [1 2 3] (3,)
Mảng 2:
 [[1 2 3]] (1, 3)
Mảng 3:
 [[[[[1]
    [2]
    [3]]]]] (1, 1, 1, 3, 1)


In [ ]:
import numpy as np

arr_1 = np.array([1,2,3])
arr_2 = np.expand_dims(arr_1, axis=0)
arr_3 = np.expand_dims(arr_2, axis=(0,2,4))

print("Mảng 1:\n", arr_1, arr_1.shape)
print("Mảng 2:\n", arr_2, arr_2.shape)
print("Mảng 3:\n", arr_3, arr_3.shape)

Mảng 1:
 [1 2 3] (3,)
Mảng 2:
 [[1 2 3]] (1, 3)
Mảng 3:
 [[[[[1]
    [2]
    [3]]]]] (1, 1, 1, 3, 1)


In [ ]:
import numpy as np

# Tạo một array 2D
arr_2D = np.array([[1,2,3],[4,5,6]])
# (2,3) -> (3,2)
new_arr_2D = np.reshape(arr_2D,(3,2))

# Chuyển từ 2D -> 1D
arr_1D = np.reshape(arr_2D, newshape=(6,))
print("array 2D:\n",arr_2D,arr_2D.shape)
print("array 2D:\n",new_arr_2D,new_arr_2D.shape)
print("array 1D:\n",arr_1D,arr_1D.shape)

array 2D:
 [[1 2 3]
 [4 5 6]] (2, 3)
array 2D:
 [[1 2]
 [3 4]
 [5 6]] (3, 2)
array 1D:
 [1 2 3 4 5 6] (6,)


In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5])
result = np.where(arr > 3)
print(result)
print("Giá trị các phần tử tại vị trí tìm được:",arr[result])

(array([3, 4]),)
Giá trị các phần tử tại vị trí tìm được: [4 5]


In [ ]:
import numpy as np
# Tạo mảng
arr = np . array ([1 , 2, 3 , 4 , 5])
# Tìm giá trị lớn nhất
max_value = np.max( arr )
print ("Giá trị lớn nhất trong mảng:", max_value )
# Tìm giá trị nhỏ nhất
min_value = np.min( arr )
print ("Giá trị nhỏ nhất trong mảng:",min_value )

Giá trị lớn nhất trong mảng: 5
Giá trị nhỏ nhất trong mảng: 1


In [ ]:
# aivietnam
import numpy as np

# Tạo mảng 2 chiều
arr2d = np . array ([[1 , 2 , 3] , [4 , 5 , 6]])
# Tìm giá trị lớn nhất theo từng chiều
max_value_row = np .max( arr2d , axis =1)
max_value_col = np .max( arr2d , axis =0)

print ("Giá trị lớn nhất theo hàng trong mảng 2 chiều:", max_value_row )
print ("Giá trị lớn nhất theo cột trong mảng 2 chiều:", max_value_col )
# Tìm giá trị nhỏ nhất theo từng chi ều
min_value_row = np .min( arr2d , axis =1)
min_value_col = np .min( arr2d , axis =0)
print ("Giá trị nhỏ nhất theo hàng trong mảng 2 chiều:", min_value_row )
print ("Giá trị nhỏ nhất theo cột trong mảng 2 chiều:", min_value_col )

Giá trị lớn nhất theo hàng trong mảng 2 chiều: [3 6]
Giá trị lớn nhất theo cột trong mảng 2 chiều: [4 5 6]
Giá trị nhỏ nhất theo hàng trong mảng 2 chi ều: [1 4]
Giá trị nhỏ nhất theo cột trong mảng 2 chiều: [1 2 3]


In [ ]:
import numpy as np

# Tạo mảng 2 chiều
arr2d = np . array ([[1 , 2 , 11] , [4 , 8 , 6]])
# Tìm chỉ số của giá trị lớn nhất trong toàn bộ mảng
index_max2d = np . argmax ( arr2d )
print ("Chỉ số của giá trị lớn nhất trong mảng 2 chiều:", index_max2d )

# Tìm chỉ số của giá trị nhỏ nhất trong toàn bộ mảng
index_min2d = np . argmin ( arr2d )
print ("Chỉ số của giá trị nhỏ nhất trong mảng 2 chiều:", index_min2d )

# Tìm chỉ số của giá trị lớn nhất theo từng hàng
index_max_row = np . argmax ( arr2d , axis =1)
print ("Chỉ số của giá trị lớn nhất theo từng hàng trong mảng 2 chiều:",index_max_row )

# Tìm chỉ số của giá trị lớn nhất theo từng cột
index_max_col = np . argmax ( arr2d , axis =0)
print ("Chỉ số của giá trị lớn nhất theo từng cột trong mảng 2 chiều:",index_max_col )

Chỉ số của giá trị lớn nhất trong mảng 2 chiều: 2
Chỉ số của giá trị nhỏ nhất trong mảng 2 chiều: 0
Chỉ số của giá trị lớn nhất theo từng hàng trong mảng 2 chiều: [2 1]
Chỉ số của giá trị lớn nhất theo từng cột trong mảng 2 chiều: [1 1 0]


In [2]:
import numpy as np

arr2d = np.array([[3,2,1],[6,0,5]])
sorted_arr2d = np.sort(arr2d)
print("Sắp xếp mảng theo mặc định: \n",sorted_arr2d)
#Sắp xếp theo từng hàng
sorted_arr2d_row = np.sort(arr2d,axis=1)
print("Sắp xếp theo từng hàng: \n",sorted_arr2d_row)
#Sắp xếp theo từng cột
sorted_arr2d_col = np.sort(arr2d,axis=0)
print("Sắp xếp theo từng cột: \n",sorted_arr2d_col)

Sắp xếp mảng theo mặc định: 
 [[1 2 3]
 [0 5 6]]
Sắp xếp theo từng hàng: 
 [[1 2 3]
 [0 5 6]]
Sắp xếp theo từng cột: 
 [[3 0 1]
 [6 2 5]]


In [4]:
import numpy as np

arr_1 = np.array([1,2,3,4])
arr_2 = np.array([5,6,7,8])

arr_add_1 = arr_1 + arr_2
arr_add_2 = np.add(arr_1,arr_2)
# In ra màn hình
print ( f" arr_1 = \n{ arr_1 }")
print ( f" arr_2 = \n{ arr_2 }")
print (" arr_1 + arr_2 ")
print ( f" arr_add_1 = \n{ arr_add_1 }")
print ( f" arr_add_2 = \n{ arr_add_2 }")



 arr_1 = 
[1 2 3 4]
 arr_2 = 
[5 6 7 8]
 arr_1 + arr_2 
 arr_add_1 = 
[ 6  8 10 12]
 arr_add_2 = 
[ 6  8 10 12]


In [5]:
import numpy as np
# Tạo hai mảng 1D
arr_1 = np . array ([1 , 2 , 3 , 4])
arr_2 = np . array ([5 , 6 , 7 , 8])
print (" arr_1 :", arr_1 )
print (" arr_2 :", arr_2 )
# Hiệu hai array
# Cách 1: Sử dụng toán tử ’-’
array_sub_1 = arr_1 - arr_2
# Cách 2: Sử dụng hàm np. subtract ()
array_sub_2 = np . subtract ( arr_1 , arr_2 )
# In ra màn hình
print ("Cách 1\n", array_sub_1 )
print ("Cách 2\n", array_sub_2 )

 arr_1 : [1 2 3 4]
 arr_2 : [5 6 7 8]
Cách 1
 [-4 -4 -4 -4]
Cách 2
 [-4 -4 -4 -4]


In [7]:
# aivietnam
import numpy as np

# Tạo hai mảng 1D
arr_1 = np . array ([1 , 2 , 3 , 4])
arr_2 = np . array ([5 , 6 , 7 , 8])
# In ra giá trị của hai array
print (" arr_1 :\n", arr_1 )
print (" arr_2 :\n", arr_2 )
# Tích hai array
# Cách 1: Sử dụng toán tử ’* ’
result_mul_1 = arr_1 * arr_2
# Cách 2: Sử dụng hàm np. multiply ()
result_mul_2 = np . multiply ( arr_1 , arr_2 )
# In ra màn hình
print ("Cách 1:\n", result_mul_1 )
print ("Cách 2:\n", result_mul_2 )

 arr_1 :
 [1 2 3 4]
 arr_2 :
 [5 6 7 8]
Cách 1:
 [ 5 12 21 32]
Cách 2:
 [ 5 12 21 32]


In [8]:
# aivietnam
import numpy as np

# Tạo hai mảng 1D
arr_1 = np . array ([1 , 2 , 3 , 4])
arr_2 = np . array ([5 , 6 , 7 , 8])
# In ra giá trị của hai array
print (" arr_1 :\n", arr_1 )
print (" arr_2 :\n", arr_2 )
# Chia hai array
# Cách 1: Sử dụng toán tử ’/ ’
result_div_1 = arr_1 / arr_2
# Cách 2: Sử dụng hàm np. divide ()
result_div_2 = np . divide ( arr_1 , arr_2 )
# In ra màn hình
print ("Cách 1:\n", result_div_1 )
print ("Cách 2:\n", result_div_2 )

 arr_1 :
 [1 2 3 4]
 arr_2 :
 [5 6 7 8]
Cách 1:
 [0.2        0.33333333 0.42857143 0.5       ]
Cách 2:
 [0.2        0.33333333 0.42857143 0.5       ]


In [1]:
# aivietnam
import numpy as np

# Tạo hai mảng 1D
arr_1 = np . array ([1 , 2])
arr_2 = np . array ([2 , 3])
# In ra giá trị của hai array
print (" arr_1 :\n", arr_1 )
print (" arr_2 :\n", arr_2 )
# Sử dụng hàm np.dot ()
result_dot = np . dot ( arr_1 , arr_2 )
# In ra màn hình
print ("Kết quả tích vô hướng arr_1 , arr_2:\n", result_dot )

 arr_1 :
 [1 2]
 arr_2 :
 [2 3]
Kết quả tích vô hướng arr_1 , arr_2:
 8


In [2]:
# aivietnam
import numpy as np

# Tạo 2 mảng 2D
arr_1 = np . array ([[1 , 2] , [3 , 4]])
arr_2 = np . array ([[5 , 6] , [7 , 8]])

# In ra giá trị của hai array
print (" arr_1 :\n", arr_1 )
print (" arr_2 :\n", arr_2 )

# Sử dụng hàm np. matmul ()
result_matmul = np . matmul ( arr_1 , arr_2 )

# In ra màn hình
print ("Kết quả tích arr_1 , arr_2 :\n",
result_matmul )

 arr_1 :
 [[1 2]
 [3 4]]
 arr_2 :
 [[5 6]
 [7 8]]
Kết quả tích arr_1 , arr_2 :
 [[19 22]
 [43 50]]


In [3]:
# aivietnam
import numpy as np

#Tạo mảng 2d
arr_1 = np . array ([[1 , 2] , [3 , 4]])
# Chuy ển vị array
# Cách 1: Sử dụng hàm np. transpose ()
arr_transposed_1 = np . transpose ( arr_1 )
# Cách 2: Sử dụng toán tử T
arr_transposed_2 = arr_1 . T
# In ra màn hình
print (" array 1:\n", arr_1 )
print (" array 1 sau khi chuy ển vị, cách 1:\n", arr_transposed_1 )
print (" array 1 sau khi chuy ển vị, cách 2:\n", arr_transposed_2 )

 array 1:
 [[1 2]
 [3 4]]
 array 1 sau khi chuy ển vị, cách 1:
 [[1 3]
 [2 4]]
 array 1 sau khi chuy ển vị, cách 2:
 [[1 3]
 [2 4]]


In [4]:
# aivietnam
import numpy as np

# Tạo mảng 2D
arr = np . array ([[1 , 2 , 3] , [4 , 5 , 6]])

# Tính tổng của tất cả các phần tử
total_sum = np .sum( arr )

# Tính tổng theo cột
column_sum = np .sum( arr , axis =0)

# Tính tổng theo hàng
row_sum = np .sum ( arr , axis =1)
# In ra màn hình
print ("Mảng :\n", arr )
print ("Tổng của tất cả các phần tử trong mảng :\n", total_sum )
print ("Tổng theo cột:\n", column_sum )
print ("Tổng theo hàng :\n", row_sum )

Mảng :
 [[1 2 3]
 [4 5 6]]
Tổng của tất cả các phần tử trong mảng :
 21
Tổng theo cột:
 [5 7 9]
Tổng theo hàng :
 [ 6 15]


In [6]:
# aivietnam
import numpy as np

# Tạo mảng 1 chiều
arr = np . array ([1 , 2, 3 , 4 , 5])

# Tính trung bình cộng các phần tử mảng
mean_value = np . mean ( arr )
print (" Trung bình cộng các phần tử trong mảng:", mean_value )

 Trung bình cộng các phần tử trong mảng: 3.0


In [8]:
# aivietnam
import numpy as np

# Tạo vector
vector = np . array ([1 , 2 , 3])

# Tính chuẩn Euclid(độ dài) của vector
norm = np . linalg . norm ( vector )
print (" Chu ẩn Euclid của vector :", norm )

 Chu ẩn Euclid của vector : 3.7416573867739413


In [10]:
# aivietnam
import numpy as np

# Tạo ma trận hệ số A
A = np . array ([[3 , 1] , [1 , 2]])
# Tạo vector hằng số b
b = np . array ([9 , 8])
# Giải hệ phương trình tuyến tính
x = np . linalg . solve (A , b )
print (" Nghi ệm của hệ phương trình:", x )

 Nghi ệm của hệ phương trình: [2. 3.]


In [11]:
# aivietnam
import numpy as np

# Tạo mảng 1 chiều
arr = np . array ([1 , 2, 3])
# Cộng số 2 vào từng phần tử của mảng
result = arr + 2
print ("Kết quả:", result )

Kết quả: [3 4 5]


In [13]:
# aivietnam
import numpy as np

# Tạo mảng 2 chiều
arr2d = np . array ([[1 , 2 , 3] , [4 , 5 , 6]])
# Tạo mảng 1 chiều
arr1d = np . array ([1 , 2 , 3])
# Cộng hai mảng
result = arr2d + arr1d
print (" array 2d:\n", arr2d )
print (" array 1d:\n", arr1d )
print ("Kết quả:\n", result )

 array 2d:
 [[1 2 3]
 [4 5 6]]
 array 1d:
 [1 2 3]
Kết quả:
 [[2 4 6]
 [5 7 9]]


In [15]:
# aivietnam
import numpy as np

# Tạo mảng 3x1
arr1 = np . array ([[1] , [2] , [3]])
# Tạo mảng 1x3
arr2 = np . array ([10 , 20 , 30])
# Nhân hai mảng
result = arr1 * arr2
print (" array 1:\n", arr1 )
print (" array 2:\n", arr2 )
print ("Kết quả:\n", result )

 array 1:
 [[1]
 [2]
 [3]]
 array 2:
 [10 20 30]
Kết quả:
 [[10 20 30]
 [20 40 60]
 [30 60 90]]


In [16]:
# aivietnam
import numpy as np

# Tạo mảng 3 chiều
arr3d = np . array ([[[1 , 2 , 3] , [4 , 5 , 6]] ,
[[7 , 8 , 9] , [10 , 11 , 12]]])

# Tạo mảng 1 chiều
arr1d = np . array ([1 , 2 , 3])

# Cộng hai mảng
result = arr3d + arr1d

print (" array 3d:\n", arr3d )
print (" array 1d:\n", arr1d )
print ("Kết quả:\n", result )

 array 3d:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
 array 1d:
 [1 2 3]
Kết quả:
 [[[ 2  4  6]
  [ 5  7  9]]

 [[ 8 10 12]
  [11 13 15]]]


In [17]:
# aivietnam
import numpy as np

# Định nghĩa hàm tính tổng
def sum_of_elements ( arr ):
  return np .sum( arr )
# Tạo mảng 2 chiều
arr2d = np . array ([[1 , 2 , 3] , [4 , 5 , 6] ,
[7 , 8 , 9]])
# Áp dụng hàm tính tổng lên từng hàng của mảng
result = np . apply_along_axis (sum_of_elements , axis =1 , arr = arr2d )
print ("Tổng các phần tử trong mỗi hàng:", result )

Tổng các phần tử trong mỗi hàng: [ 6 15 24]


In [19]:
# aivietnam
import numpy as np

# Định nghĩa hàm chuy ển đổi nhiệt độ
def celsius_to_fahrenheit ( c ) :
  return ( c * 9/5) + 32
# Vector hóa hàm celsius_to_fahrenheit
vectorized_conversion = np . vectorize (celsius_to_fahrenheit )
# Tạo mảng nhiệt độ Celsius
celsius = np . array ([0 , 20 , 37 , 100])
# Áp dụng hàm vector hóa lên mảng
fahrenheit = vectorized_conversion ( celsius)
print (" Chuy ển đổi từ Celsius sang Fahrenheit :", fahrenheit )

 Chuy ển đổi từ Celsius sang Fahrenheit : [ 32.   68.   98.6 212. ]
